log: debug
api:
  templates:
    - subtopic: json
      retain: false
      template: >-
        {
          "device": "${onvifDeviceId}",
          "event": "${eventType}"
          "state": "${eventState}"
        }
mqtt:
  host: 192.168.68.121
  port: 1883
onvif:
  - name: doorbell
    hostname: 192.168.68.124
    port: 80
    username: admin
    password: SHAGCB
